general:
  fixed_sys: False
  acc_once: False
  num_pp: -1
  num_topos: 1
  num_jobs: 1
  optimization: ppa
  work_dir: test_pipe_alexnet
  keep_dir: True

workload:
  name: alexnet
  input-size: [ 1, 3, 227, 227 ]

pipeline:
  stages:
    - WorkloadParser
    - SystemParser
    - GraphAnalysis
    - NodeEvaluation
    - PartitioningOptimization
    - ExportPartitionResults

system:
  compute:
    - id: 0
      bits: 8
      fault_rates: [0, 0] # input, weight
      max_memory_size: 600000000
      dse:
        optimization: eap
        top_k: 1
        constraints:
          mesh_dim_min: 16
          mesh_dim_max: 16
          min_spad_size: 64
          max_spad_size: 128
          min_acc_size: 64
          max_acc_size: 128
        mutator: GemminiArchitectureMutator
      evaluation:
        accelerator: gemmini_like
        simulator: timeloop
        frequency: 200000000
        layer: conv2d
        mapper:
          algorithm: random-pruned
          live-status: false
          max-permutations-per-if-visit: 16
          num-threads: 200
          optimization-metrics:
          - edp
          timeout: 15000
          victory-condition: 500
    - id: 2
      bits: 8
      max_memory_size: 600000000
      evaluation:
        accelerator: simba_like
        simulator: timeloop
        frequency: 200000000
        layer: conv2d
        mapper:
          algorithm: random-pruned
          live-status: false
          max-permutations-per-if-visit: 16
          num-threads: 8
          optimization-metrics:
          - edp
          timeout: 15000
          victory-condition: 500
  link:
    - id: 1
      max_out_size: 20000000
      data_bit_width: 8
      noi:
        noi_mode: UCIe
        width: 16
        data_rate_Gbps: 4
        latency_ns: 2 # including D2D Adapter and PHY
        power_bit_pj: 0.5
      fps: 25