problem:
  instance:
    C: 128
    Hdilation: 1
    Hstride: 1
    M: 256
    N: 1
    P: 56
    Q: 56
    R: 3
    S: 3
    Wdilation: 1
    Wstride: 1
  shape:
    coefficients:
    - default: 1
      name: Hdilation
    - default: 1
      name: Wdilation
    - default: 1
      name: Hstride
    - default: 1
      name: Wstride
    data-spaces:
    - name: Weights
      projection:
      - - - M
      - - - C
      - - - R
      - - - S
    - name: Inputs
      projection:
      - - - N
      - - - C
      - - - R
          - Wdilation
        - - P
          - Wstride
      - - - S
          - Hdilation
        - - Q
          - Hstride
    - name: Outputs
      projection:
      - - - N
      - - - M
      - - - Q
      - - - P
      read-write: true
    dimensions:
    - C
    - M
    - R
    - S
    - N
    - P
    - Q
    name: CNN-Layer
