general:
  fixed_sys: False
  acc_once: False
  num_pp: -1
  num_topos: 1
  num_jobs: 1
  optimization: all
  work_dir: alexnet_coopt_test
  keep_dir: True

workload:
  name: alexnet
  input-size: [ 1, 3, 227, 227 ]

pipeline:
  stages:
    - WorkloadParser
    - SystemParser
    - GraphAnalysis
    - DesignPartitioningOptimization

dse:
  problem: DesignProblem
  algorithm: nsga2
  optimization: edp

components:
  - id: 0
    bits: 16
    fault_rates: [0, 0] # input, weight
    max_memory_size: 600000000
    dse:
      optimization: edap
      min_pe: [8, 8]
      max_pe: [32, 32]
      min_size_mem_shared: [512] #in byte
      max_size_mem_shared: [1024] #in byte 
      min_size_mem_local: [128, 128, 128]
      max_size_mem_local: [128, 128, 128]
    timeloop:
      accelerator: eyeriss_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
  - id: 1
    max_out_size: 20000000
    data_bit_width: 8
    noi:
      noi_mode: UCIe
      width: 16
      data_rate_Gbps: 4
      latency_ns: 2 # including D2D Adapter and PHY
      power_bit_pj: 0.5
    fps: 25
  - id: 2
    bits: 8
    max_memory_size: 600000000
    timeloop:
      accelerator: simba_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500

