neural-network:
  name: fcn_resnet50
  input-size: [ 1, 3, 224, 224 ]

sensor:
  timeloop:
    layer: conv2d
    accelerator: simba_like
    frequency: 500000000
    mapper:
      optimization-metrics: [ delay, energy ]
      live-status: False
      num-threads: 8
      timeout: 0
      victory-condition: 100
      algorithm: linear-pruned

link:
  data_bit_width: 16
  fps: 25
  ethernet:
    eth_mode : "BASE1000-T"
    cable_len_m : 5
    enable_eee : False
    eee_lmi_ratio : 0.1
    eee_toff_ms : 0

edge:
  device : "cpu"
  max_threads : 10
  num_runs : 500

constraints:
  max_out_size : 450000
