general:
  fixed_sys: True
  num_pp: 1
  num_topos: 1
  num_jobs: 64

neural-network:
  name: fcnresnet50
  input-size: [ 1, 3, 224, 224 ]

accuracy:
  device: "cuda"
  bits: [16, 8] # eyeriss 16-bit, simba 8-bit
  robustness:
    pop_size: 32
    num_gen: 64
    bits: [4, 6, 8, 16]
    min_acc: 0.65
  calibration:
    samples: null # null sets samples to all
    file: './calibrations/fcnresnet50_quant_calib.pkl'
  retraining:
    epochs: 2
  datasets:
    calibrate:
      type: coco
      kind: 'imagefolder'
      path: '/tools/datasets/coco-stuff/val2017'
      sample_limit: null # number of validation dataset samples to test for each individual
      batch_size: 64
      randomize: False
    validation:
      type: coco
      kind: 'imagefolder'
      path: '/tools/datasets/coco-stuff/val2017'
      sample_limit: 5000 # number of validation dataset samples to test for each individual
      batch_size: 256
      randomize: False
    train:
      type: coco
      kind: 'imagefolder'
      path: '/tools/datasets/coco-stuff/train2017'
      total_samples: 118287
      batch_size: 256
      sample_limit: null

components:
  - id: 0
    bits: 16
    max_memory_size: 600000000
    timeloop:
      accelerator: eyeriss_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: linear-pruned
        live-status: false
        num-threads: 8
        timeout: 0
        victory-condition: 100
  - id: 1
    max_out_size: 150000000
    data_bit_width: 16
    ethernet:
      cable_len_m: 5
      eee_lmi_ratio: 0.1
      eee_toff_ms: 0
      enable_eee: false
      eth_mode: BASE1000-T
    fps: 25
  - id: 2
    bits: 8
    max_memory_size: 600000000
    timeloop:
      accelerator: simba_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: linear-pruned
        live-status: false
        num-threads: 8
        timeout: 0
        victory-condition: 100
