general:
  fixed_sys: False
  acc_once: False
  num_pp: -1
  num_topos: 1
  num_jobs: 1
  optimization: all

workload:
  name: fcnresnet101
  input-size: [ 1, 3, 224, 224 ]

pipeline:
  stages:
    - WorkloadParser
    - SystemParser
    - GraphAnalysis
    - RobustnessOptimization
    - NodeEvaluation
    - PartitioningOptimization
    - AccuracyEvaluation
    - ExportPartitionResults

accuracy:
  robustness:
    bits: [4, 6, 8, 16]
    delta : 0.01 # best_acc - delta = lower boundary for the selection of the bit constraints
  retraining:
    epochs: 0
  datasets:
    calibrate:
      type: coco
      kind: 'imagefolder'
      path: '/tools/datasets/coco-stuff/val2017'
      sample_limit: 8192
      batch_size: 64
      randomize: False
      file: './calibrations/fcnresnet101_quant_calib.pkl'
    validation:
      type: coco
      kind: 'imagefolder'
      path: '/tools/datasets/coco-stuff/val2017'
      sample_limit: 5000 # number of validation dataset samples to test for each individual
      batch_size: 256
      randomize: False
    train:
      type: coco
      kind: 'imagefolder'
      path: '/tools/datasets/coco-stuff/train2017'
      total_samples: 118287
      batch_size: 256
      sample_limit: null

components:
  - id: 0
    bits: 16
    max_memory_size: 600000000
    timeloop:
      accelerator: eyeriss_like1
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
  - id: 1
    max_out_size: 20000000
    data_bit_width: 8
    noi:
      noi_mode: UCIe
      width: 16
      data_rate_Gbps: 4
      latency_ns: 2 # including D2D Adapter and PHY
      power_bit_pj: 0.5
    fps: 25
  - id: 2
    bits: 8
    max_memory_size: 600000000
    timeloop:
      accelerator: eyeriss_like2
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
  - id: 3
    bits: 8
    max_memory_size: 600000000
    timeloop:
      accelerator: eyeriss_like3
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
  - id: 4
    bits: 8
    max_memory_size: 600000000
    timeloop:
      accelerator: eyeriss_like4
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
