constraints: {max_out_size: 200000,  max_memory_size: 6000000, word_width: 16}
optimization-objectives:
  component: 0
  metric: latency

neural-network:
  input-size: [1, 3, 224, 224]
  name: googlenet

accuracy:
  device : "cuda"
  bits: [32, 8]
  calibration:
    samples: null # null sets samples to all
    file: './calibrations/googlenet_quant_calib.pkl'
    datasets:
      calibrate:
        type: imagenet
        kind: 'imagefolder'
        path: '/tools/datasets/imagenet/val_images'
        sample_limit: null # number of validation dataset samples to test for each individual
        batch_size: 64
        randomize: True

components:
  - id: 0
    name: sensor #optional
    timeloop:
      accelerator: eyeriss_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: linear-pruned
        live-status: false
        num-threads: 8
        optimization-metrics: [energy, delay]
        timeout: 0
        victory-condition: 100
  - id: 1
    data_bit_width: 16
    ethernet:
      cable_len_m: 5
      eee_lmi_ratio: 0.1
      eee_toff_ms: 0
      enable_eee: false
      eth_mode: BASE1000-T
    fps: 25
  - id: 2
    name: edge
    device: cuda
    max_threads: 10
    num_runs: 500