general:
  fixed_sys: False
  acc_once: False
  num_pp: -1
  num_topos: 1
  num_jobs: 1
  optimization: all

workload:
  name: regnet_x_400mf
  input-size: [ 1, 3, 227, 227 ]

pipeline:
  stages:
    - WorkloadParser
    - SystemParser
    - GraphAnalysis
    - RobustnessOptimization
    - NodeEvaluation
    - PartitioningOptimization
    - AccuracyEvaluation
    - ExportPartitionResults

accuracy:
  robustness:
    bits: [4, 6, 8, 16]
    delta : 0.01 # best_acc - delta = lower boundary for the selection of the bit constraints
  retraining:
    epochs: 0
  datasets:
    calibrate:
      type: imagenet
      kind: 'imagefolder'
      path: '/tools/datasets/imagenet/val_images'
      sample_limit: 8192
      batch_size: 64
      randomize: False
      file: './calibrations/regnet_x_400mf_quant_calib.pkl'
    validation:
      type: imagenet
      kind: 'imagefolder'
      path: '/tools/datasets/imagenet/val_images'
      sample_limit: 8192 # number of validation dataset samples to test for each individual
      batch_size: 256
      randomize: False
    train:
      type: imagenet
      kind: 'webdataset'
      path: '/tools/datasets/imagenet/train/imagenet-train-{0000..0136}.tar'
      total_samples: 1281167
      batch_size: 256
      sample_limit: null

components:
  - id: 0
    bits: 16
    fault_rates: [0, 0] # input, weight
    max_memory_size: 600000000
    timeloop:
      accelerator: eyeriss_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
  - id: 1
    max_out_size: 150000000
    data_bit_width: 16
    ethernet:
      cable_len_m: 5
      eee_lmi_ratio: 0.1
      eee_toff_ms: 0
      enable_eee: false
      eth_mode: BASE1000-T
    fps: 25
  - id: 2
    bits: 8
    fault_rates: [0, 0] # input, weight
    max_memory_size: 600000000
    timeloop:
      accelerator: simba_like
      frequency: 200000000
      layer: conv2d
      mapper:
        algorithm: random-pruned
        live-status: false
        max-permutations-per-if-visit: 16
        num-threads: 8
        optimization-metrics:
        - edp
        timeout: 15000
        victory-condition: 500
