general:
  fixed_sys: true
  acc_once: true
  num_pp: 1
  num_topos: 1
  num_jobs: 64
  optimization: ppa
  work_dir: runs/resnext50_run
  keep_dir: false

workload:
  name: resnext50
  input-size: [1, 3, 227, 227]

pipeline:
  stages:
  - WorkloadParser
  - SystemParser
  - GraphAnalysis
  - RobustnessOptimization
  - NodeEvaluation
  - PartitioningOptimization
  - AccuracyEvaluation
  - ExportPartitionResults

components:
- id: 0
  bits: 8
  fault_rates: [0, 0]   # input, weight
  max_memory_size: 600000000
  evaluation:
    accelerator: eyeriss_like
    frequency: 200000000
    layer: conv2d
    mapper:
      algorithm: random-pruned
      live-status: false
      max-permutations-per-if-visit: 16
      num-threads: 200
      optimization-metrics:
      - edp
      timeout: 15000
      victory-condition: 500
    simulator: timeloop
- id: 1
  max_out_size: 150000000
  data_bit_width: 16
  ethernet:
    cable_len_m: 5
    eee_lmi_ratio: 0.1
    eee_toff_ms: 0
    enable_eee: false
    eth_mode: BASE1000-T
  fps: 25
- id: 2
  bits: 8
  max_memory_size: 600000000
  evaluation:
    accelerator: simba_like
    frequency: 200000000
    layer: conv2d
    mapper:
      algorithm: random-pruned
      live-status: false
      max-permutations-per-if-visit: 16
      num-threads: 200
      optimization-metrics:
      - edp
      timeout: 15000
      victory-condition: 500
    simulator: timeloop
