constraints: {max_out_size: 150000,  max_memory_size: 3060000, word_width: 16}
optimization-objectives: {device: sensor, metric: latency}
edge: {device: cpu, max_threads: 10, num_runs: 500}
link:
  data_bit_width: 16
  ethernet: {cable_len_m: 5, eee_lmi_ratio: 0.1, eee_toff_ms: 0, enable_eee: false,
    eth_mode: BASE1000-T}
  fps: 25
neural-network:
  input-size: [1, 3, 227, 227]
  name: squeezenet1_1
  input-size: [ 1, 3, 227, 227 ]

accuracy:
  device : "cuda"
  bits: [8, 32]
  calibration:
    samples: null # null sets samples to all
    file: './calibrations/squeezenet1_1_quant_calib.pkl'
    datasets:
      calibrate:
        type: imagenet
        kind: 'imagefolder'
        path: '/tools/datasets/imagenet/val_images'
        sample_limit: null # number of validation dataset samples to test for each individual
        batch_size: 64
        randomize: True

sensor:
  timeloop:
    accelerator: simba_like
    frequency: 500000000
    layer: conv2d
    mapper:
      algorithm: linear-pruned
      live-status: false
      num-threads: 8
      optimization-metrics: [energy, delay]
      timeout: 0
      victory-condition: 10
