constraints:
  max_out_size: 15000 # must be link specific
  max_memory_size: 20000000
  word_width: 16

optimization-objectives:
  component: 0
  metric: latency

neural-network:
  name: squeezenet1_1
  input-size: [ 1, 3, 227, 227 ]

accuracy:
  device : "cuda"
  bits: [16, 16]
  calibration:
    samples: null # null sets samples to all
    file: './calibrations/squeezenet1_1_quant_calib.pkl'
  retraining:
    epochs: 2
  datasets:
    calibrate:
      type: imagenet
      kind: 'imagefolder'
      path: '/tools/datasets/imagenet/val_images'
      sample_limit: null # number of validation dataset samples to test for each individual
      batch_size: 16
      randomize: True
    validation:
      type: imagenet
      kind: 'imagefolder'
      path: '/tools/datasets/imagenet/val_images'
      sample_limit: 8192 # number of validation dataset samples to test for each individual
      batch_size: 32
      randomize: True
    train:
      type: imagenet
      kind: 'webdataset'
      path: '/tools/datasets/imagenet/train/imagenet-train-{0000..0136}.tar'
      total_samples: 1281167
      batch_size: 32
      sample_limit: null

components:
  - id: 0
    max_memory_size: 3000000
    timeloop:
      accelerator: eyeriss_like
      frequency: 500000000
      layer: conv2d
      mapper:
        algorithm: linear-pruned
        live-status: false
        num-threads: 8
        timeout: 0
        victory-condition: 100
  - id: 1
    memory: DDR3
    fps: 25
  - id: 2
    max_memory_size: 3000000
    mnsim:
      conf_path: '/configs/mnsim_configs/SimConfig.ini'
