constraints: {max_out_size: 450000}
optimization-objective: 
  device: senosr
  metric: energy
edge: {device: cpu, max_threads: 10, num_runs: 500}
link:
  data_bit_width: 16
  ethernet: {cable_len_m: 5, eee_lmi_ratio: 0.1, eee_toff_ms: 0, enable_eee: false,
    eth_mode: BASE1000-T}
  fps: 25
neural-network:
  input-size: [1, 3, 224, 224]
  name: vgg19
sensor:
  timeloop:
    accelerator: simple_output_stationary
    frequency: 200000000
    layer: conv2d
    mapper:
      algorithm: linear-pruned
      live-status: false
      num-threads: 8
      optimization-metrics: [energy, delay]
      timeout: 0
      victory-condition: 100
